language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
jobs:
  include:
    - name: flake8
      python: 3.8
      env: TOXENV=flake8
install:
  - pip install tox-travis
script:
  - tox
notifications:
  email: false
cache: pip
