language: python
cache: pip
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - pypy
  - pypy3
install:
  - pip install pytest coverage coverage-python-version
script:
  - coverage run pytest
  - coverage report -m --fail-under=100

notifications:
  irc:
    channels:
      - "chat.freenode.net##mgedmin"
    on_success: change
    on_failure: always
    template:
      # ping my nick so I get a pushbullet notification on my phone
      - "mgedmin: %{repository_name} (%{branch}) build %{result}: %{build_url}"
