#!/bin/sh
set -e

check() {
    url=$1
    contains=$2
    page=$(curl -sSL "$url")
    printf "%s" "$page" | grep -q "$contains" || {
        printf '%s did not contain "%s"!\n' "$url" "$contains" 1>&2
        printf '======== %s\n%s\n--------\n' "$url" "$page"
        return 1
    }
}

set -x
chmod +x /root
echo "This is the changelog" > /root/Changelog
echo "This is the MOTD" > /etc/motd
pov-update-server-page -v enabled=1 loopback_only=1 canonical_redirect=0 disk_usage=all
htpasswd -b -c /etc/pov/fridge.passwd test testpwd
a2enmod ssl rewrite headers cgid
a2query -s
hostname=$(hostname -f)
a2ensite "$hostname.conf"
a2dissite 000-default
a2query -s
service apache2 reload
auth=test:testpwd
check http://"$auth@$hostname"/          "This is the MOTD"
check http://"$auth@$hostname"/info      "Last updated"
check http://"$auth@$hostname"/changelog "This is the changelog"
check http://"$auth@$hostname"/stats     "Server stats"
check http://"$auth@$hostname"/ports     "Open TCP"
check http://"$auth@$hostname"/du        "Disk Usage"
